const fs = require('fs');
const lines = [];
lines.push("'use client'");
lines.push("");
lines.push("import { useEffect, useState } from 'react'");
lines.push("import { supabase } from '@/lib/supabase'");
lines.push("import Navbar from '@/components/Navbar'");
lines.push("");
lines.push("interface Booking {");
lines.push("  id: string");
lines.push("  booking_date: string");
lines.push("  start_time: string");
lines.push("  end_time: string");
lines.push("  team_name: string");
lines.push("  purpose: string");
lines.push("  status: string");
lines.push("  pitch_id: number");
lines.push("  pitch_name: string");
lines.push("  pitch_colour: string");
lines.push("}");
lines.push("");
lines.push("const fmt = (t: string) => { const parts = t.slice(0,5).split(':'); const hr = parseInt(parts[0]); const mn = parts[1]; return `${hr > 12 ? hr-12 : hr === 0 ? 12 : hr}:${mn}${hr >= 12 ? 'pm' : 'am'}` }");
lines.push("const formatDate = (d: string) => new Date(d + 'T00:00:00').toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' })");
lines.push("");
lines.push("export default function MyBookingsPage() {");
lines.push("  const [bookings, setBookings] = useState<Booking[]>([])");
lines.push("  const [userRole, setUserRole] = useState('')");
lines.push("  const [loading, setLoading] = useState(true)");
lines.push("  const [cancelling, setCancelling] = useState<string | null>(null)");
lines.push("  const [statusFilter, setStatusFilter] = useState('all')");
lines.push("  const [timeFilter, setTimeFilter] = useState('upcoming')");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    async function init() {");
lines.push("      const { data: { session } } = await supabase.auth.getSession()");
lines.push("      if (!session) { window.location.href = '/login'; return }");
lines.push("      const { data: profile } = await supabase.from('profiles').select('role, is_approved').eq('id', session.user.id).single()");
lines.push("      if (!profile || !profile.is_approved) { window.location.href = '/pending'; return }");
lines.push("      setUserRole(profile.role || '')");
lines.push("      const { data } = await supabase");
lines.push("        .from('public_planner')");
lines.push("        .select('*')");
lines.push("        .eq('user_id', session.user.id)");
lines.push("        .not('status', 'eq', 'cancelled')");
lines.push("        .order('booking_date', { ascending: true })");
lines.push("        .order('start_time', { ascending: true })");
lines.push("      if (data) setBookings(data as Booking[])");
lines.push("      setLoading(false)");
lines.push("    }");
lines.push("    init()");
lines.push("  }, [])");
lines.push("");
lines.push("  async function handleCancel(id: string) {");
lines.push("    if (!confirm('Are you sure you want to cancel this booking?')) return");
lines.push("    setCancelling(id)");
lines.push("    const { error } = await supabase.from('bookings').update({ status: 'cancelled' }).eq('id', id)");
lines.push("    if (error) { alert('Failed to cancel. Please try again.'); setCancelling(null); return }");
lines.push("    setBookings(prev => prev.filter(b => b.id !== id))");
lines.push("    setCancelling(null)");
lines.push("  }");
lines.push("");
lines.push("  const today = new Date().toISOString().split('T')[0]");
lines.push("");
lines.push("  const filtered = bookings.filter(b => {");
lines.push("    if (timeFilter === 'upcoming' && b.booking_date < today) return false");
lines.push("    if (timeFilter === 'past' && b.booking_date >= today) return false");
lines.push("    if (statusFilter !== 'all' && b.status !== statusFilter) return false");
lines.push("    return true");
lines.push("  })");
lines.push("");
lines.push("  function BookingCard({ b }: { b: Booking }) {");
lines.push("    const isApproved = b.status === 'approved'");
lines.push("    const isPending = b.status === 'pending'");
lines.push("    const colour = b.pitch_colour || '#2e7d32'");
lines.push("    const borderColour = isPending ? '#f9ab2b' : colour");
lines.push("    const borderStyle = isPending ? 'dashed' : 'solid'");
lines.push("    return (");
lines.push("      <div style={{ backgroundColor: 'white', borderRadius: '8px', borderLeft: `4px ${borderStyle} ${borderColour}`, padding: '10px 14px', marginBottom: '8px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', boxShadow: '0 1px 2px rgba(0,0,0,0.05)' }}>");
lines.push("        <div style={{ flex: 1 }}>");
lines.push("          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>");
lines.push("            <span style={{ fontWeight: '600', fontSize: '13px', color: '#111' }}>{formatDate(b.booking_date)}</span>");
lines.push("            <span style={{ fontSize: '13px', color: '#374151' }}>{fmt(b.start_time)} \u2013 {fmt(b.end_time)}</span>");
lines.push("            <span style={{ fontSize: '13px', fontWeight: '600', color: colour }}>{b.pitch_name}</span>");
lines.push("          </div>");
lines.push("          <div style={{ fontSize: '12px', color: '#6b7280', marginTop: '2px' }}>{b.team_name} \u00b7 {b.purpose}</div>");
lines.push("        </div>");
lines.push("        <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginLeft: '12px' }}>");
lines.push("          <span style={{ fontSize: '12px', fontWeight: '600', color: isApproved ? '#16a34a' : '#d97706', whiteSpace: 'nowrap' }}>{isApproved ? '● Booked' : '● Awaiting'}</span>");
lines.push("          <a href={`/edit-booking/${b.id}`} style={{ padding: '4px 10px', borderRadius: '6px', border: '1px solid #d1d5db', fontSize: '12px', color: '#374151', textDecoration: 'none', whiteSpace: 'nowrap' }}>Edit</a>");
lines.push("          <button onClick={() => handleCancel(b.id)} disabled={cancelling === b.id} style={{ padding: '4px 10px', borderRadius: '6px', border: '1px solid #fca5a5', fontSize: '12px', color: '#dc2626', backgroundColor: 'white', cursor: 'pointer', whiteSpace: 'nowrap' }}>");
lines.push("            {cancelling === b.id ? '...' : 'Cancel'}");
lines.push("          </button>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    )");
lines.push("  }");
lines.push("");
lines.push("  if (loading) return (");
lines.push("    <div style={{ minHeight: '100vh', backgroundColor: '#f4f4f4' }}>");
lines.push("      <Navbar activePage=\"My Bookings\" userRole={userRole} />");
lines.push("      <div style={{ textAlign: 'center', padding: '48px', color: '#888' }}>Loading...</div>");
lines.push("    </div>");
lines.push("  )");
lines.push("");
lines.push("  return (");
lines.push("    <div style={{ minHeight: '100vh', backgroundColor: '#f4f4f4' }}>");
lines.push("      <Navbar activePage=\"My Bookings\" userRole={userRole} />");
lines.push("      <div style={{ maxWidth: '900px', margin: '0 auto', padding: '24px 16px' }}>");
lines.push("");
lines.push("        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px', flexWrap: 'wrap', gap: '12px' }}>");
lines.push("          <div>");
lines.push("            <h1 style={{ fontSize: '22px', fontWeight: 'bold', color: '#111' }}>&#x1f4cb; My Bookings</h1>");
lines.push("            <p style={{ fontSize: '13px', color: '#6b7280', marginTop: '2px' }}>View, edit or cancel your pitch requests</p>");
lines.push("          </div>");
lines.push("          <a href=\"/new-booking\" style={{ backgroundColor: '#111', color: 'white', padding: '8px 16px', borderRadius: '8px', fontSize: '13px', fontWeight: '600', textDecoration: 'none' }}>+ New Booking</a>");
lines.push("        </div>");
lines.push("");
lines.push("        <div style={{ display: 'flex', gap: '10px', marginBottom: '16px', flexWrap: 'wrap' }}>");
lines.push("          <div style={{ display: 'flex', border: '1px solid #d1d5db', borderRadius: '8px', overflow: 'hidden' }}>");
lines.push("            {['upcoming', 'past', 'all'].map(f => (");
lines.push("              <button key={f} onClick={() => setTimeFilter(f)} style={{ padding: '6px 14px', fontSize: '12px', fontWeight: '500', backgroundColor: timeFilter === f ? '#111' : 'white', color: timeFilter === f ? 'white' : '#374151', border: 'none', cursor: 'pointer', textTransform: 'capitalize' }}>{f === 'all' ? 'All Dates' : f.charAt(0).toUpperCase() + f.slice(1)}</button>");
lines.push("            ))}");
lines.push("          </div>");
lines.push("          <div style={{ display: 'flex', border: '1px solid #d1d5db', borderRadius: '8px', overflow: 'hidden' }}>");
lines.push("            {[['all', 'All Status'], ['approved', 'Booked'], ['pending', 'Awaiting']].map(([val, label]) => (");
lines.push("              <button key={val} onClick={() => setStatusFilter(val)} style={{ padding: '6px 14px', fontSize: '12px', fontWeight: '500', backgroundColor: statusFilter === val ? '#111' : 'white', color: statusFilter === val ? 'white' : '#374151', border: 'none', cursor: 'pointer' }}>{label}</button>");
lines.push("            ))}");
lines.push("          </div>");
lines.push("          <span style={{ fontSize: '12px', color: '#6b7280', alignSelf: 'center' }}>{filtered.length} booking{filtered.length !== 1 ? 's' : ''}</span>");
lines.push("        </div>");
lines.push("");
lines.push("        {filtered.length === 0 ? (");
lines.push("          <div style={{ textAlign: 'center', padding: '48px', color: '#888', backgroundColor: 'white', borderRadius: '10px' }}>");
lines.push("            <p style={{ fontSize: '15px', marginBottom: '12px' }}>No bookings found</p>");
lines.push("            <a href=\"/new-booking\" style={{ backgroundColor: '#111', color: 'white', padding: '8px 16px', borderRadius: '8px', fontSize: '13px', fontWeight: '600', textDecoration: 'none' }}>Make a booking</a>");
lines.push("          </div>");
lines.push("        ) : (");
lines.push("          <div>{filtered.map(b => <BookingCard key={b.id} b={b} />)}</div>");
lines.push("        )}");
lines.push("      </div>");
lines.push("    </div>");
lines.push("  )");
lines.push("}");
fs.writeFileSync('app/my-bookings/page.tsx', lines.join('\n'), 'utf8');
console.log('Done');
