const fs = require('fs');
const lines = [];
lines.push("'use client'");
lines.push("");
lines.push("import { useEffect, useState } from 'react'");
lines.push("import { supabase } from '@/lib/supabase'");
lines.push("import { format, startOfMonth, endOfMonth, startOfWeek, endOfWeek, addDays, addWeeks, subWeeks, addMonths, subMonths, isSameMonth, isSameDay, isToday } from 'date-fns'");
lines.push("");
lines.push("interface Booking {");
lines.push("  id: string");
lines.push("  booking_date: string");
lines.push("  start_time: string");
lines.push("  end_time: string");
lines.push("  team_name: string");
lines.push("  purpose: string");
lines.push("  status: string");
lines.push("  pitch_id: number");
lines.push("  user_id: string");
lines.push("  pitch_name?: string");
lines.push("  pitch_colour?: string");
lines.push("  booked_by?: string");
lines.push("}");
lines.push("");
lines.push("interface Pitch {");
lines.push("  id: number");
lines.push("  name: string");
lines.push("  colour: string");
lines.push("}");
lines.push("");
lines.push("interface BookingModalProps {");
lines.push("  booking: Booking");
lines.push("  onClose: () => void");
lines.push("  currentUserId: string");
lines.push("  userRole: string");
lines.push("}");
lines.push("");
lines.push("function BookingModal({ booking, onClose, currentUserId, userRole }: BookingModalProps) {");
lines.push("  const canEdit = booking.user_id === currentUserId || userRole === 'admin'");
lines.push("  const statusColour = booking.status === 'approved' ? 'bg-green-100 text-green-800' : booking.status === 'pending' ? 'bg-yellow-100 text-yellow-800' : 'bg-red-100 text-red-800'");
lines.push("  return (");
lines.push("    <div className=\"fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4\">");
lines.push("      <div className=\"bg-white rounded-2xl shadow-xl w-full max-w-md p-6\">");
lines.push("        <div className=\"flex items-start justify-between mb-4\">");
lines.push("          <div>");
lines.push("            <h2 className=\"text-xl font-bold text-gray-900\">{booking.team_name}</h2>");
lines.push("            <p className=\"text-gray-500 text-sm mt-1\">{booking.purpose}</p>");
lines.push("          </div>");
lines.push("          <button onClick={onClose} className=\"text-gray-400 hover:text-gray-600 text-2xl leading-none\">&times;</button>");
lines.push("        </div>");
lines.push("        <div className=\"space-y-3 text-sm\">");
lines.push("          <div className=\"flex justify-between\">");
lines.push("            <span className=\"text-gray-500\">Date</span>");
lines.push("            <span className=\"font-medium\">{booking.booking_date}</span>");
lines.push("          </div>");
lines.push("          <div className=\"flex justify-between\">");
lines.push("            <span className=\"text-gray-500\">Time</span>");
lines.push("            <span className=\"font-medium\">{booking.start_time.slice(0,5)} - {booking.end_time.slice(0,5)}</span>");
lines.push("          </div>");
lines.push("          <div className=\"flex justify-between\">");
lines.push("            <span className=\"text-gray-500\">Pitch</span>");
lines.push("            <span className=\"font-medium\">{booking.pitch_name || 'Unknown'}</span>");
lines.push("          </div>");
lines.push("          <div className=\"flex justify-between\">");
lines.push("            <span className=\"text-gray-500\">Booked by</span>");
lines.push("            <span className=\"font-medium\">{booking.booked_by || 'Unknown'}</span>");
lines.push("          </div>");
lines.push("          <div className=\"flex justify-between items-center\">");
lines.push("            <span className=\"text-gray-500\">Status</span>");
lines.push("            <span className={`px-2 py-1 rounded-full text-xs font-medium ${statusColour}`}>{booking.status}</span>");
lines.push("          </div>");
lines.push("        </div>");
lines.push("        {canEdit && (");
lines.push("          <div className=\"mt-6\">");
lines.push("            <a href={`/edit-booking/${booking.id}`} className=\"block w-full bg-gray-900 text-white text-center py-3 rounded-lg font-semibold text-sm hover:bg-gray-700 transition-colors\">");
lines.push("              Edit Booking");
lines.push("            </a>");
lines.push("          </div>");
lines.push("        )}");
lines.push("      </div>");
lines.push("    </div>");
lines.push("  )");
lines.push("}");
lines.push("");
lines.push("export default function PitchCalendar({ userRole, currentUserId }: { userRole: string; currentUserId: string }) {");
lines.push("  const [currentDate, setCurrentDate] = useState(new Date())");
lines.push("  const [view, setView] = useState<'month' | 'week'>('month')");
lines.push("  const [bookings, setBookings] = useState<Booking[]>([])");
lines.push("  const [pitches, setPitches] = useState<Pitch[]>([])");
lines.push("  const [selectedPitch, setSelectedPitch] = useState('all')");
lines.push("  const [selectedTeam, setSelectedTeam] = useState('all')");
lines.push("  const [selectedBooking, setSelectedBooking] = useState<Booking | null>(null)");
lines.push("  const [loading, setLoading] = useState(true)");
lines.push("");
lines.push("  useEffect(() => { fetchPitches() }, [])");
lines.push("  useEffect(() => { fetchBookings() }, [currentDate, view])");
lines.push("");
lines.push("  async function fetchPitches() {");
lines.push("    const { data } = await supabase.from('pitches').select('id, name, colour').eq('is_active', true).order('sort_order')");
lines.push("    if (data) setPitches(data)");
lines.push("  }");
lines.push("");
lines.push("  async function fetchBookings() {");
lines.push("    setLoading(true)");
lines.push("    let start: Date, end: Date");
lines.push("    if (view === 'month') {");
lines.push("      start = startOfWeek(startOfMonth(currentDate), { weekStartsOn: 1 })");
lines.push("      end = endOfWeek(endOfMonth(currentDate), { weekStartsOn: 1 })");
lines.push("    } else {");
lines.push("      start = startOfWeek(currentDate, { weekStartsOn: 1 })");
lines.push("      end = endOfWeek(currentDate, { weekStartsOn: 1 })");
lines.push("    }");
lines.push("    const { data: bookingData } = await supabase");
lines.push("      .from('bookings')");
lines.push("      .select('id, booking_date, start_time, end_time, team_name, purpose, status, pitch_id, user_id')");
lines.push("      .gte('booking_date', format(start, 'yyyy-MM-dd'))");
lines.push("      .lte('booking_date', format(end, 'yyyy-MM-dd'))");
lines.push("      .order('start_time')");
lines.push("    if (!bookingData) { setLoading(false); return }");
lines.push("    const { data: profileData } = await supabase.from('profiles').select('id, full_name')");
lines.push("    const { data: pitchData } = await supabase.from('pitches').select('id, name, colour')");
lines.push("    const enriched = bookingData.map(b => ({");
lines.push("      ...b,");
lines.push("      pitch_name: pitchData?.find(p => p.id === b.pitch_id)?.name || '',");
lines.push("      pitch_colour: pitchData?.find(p => p.id === b.pitch_id)?.colour || '#1a5c2e',");
lines.push("      booked_by: profileData?.find(p => p.id === b.user_id)?.full_name || '',");
lines.push("    }))");
lines.push("    setBookings(enriched)");
lines.push("    setLoading(false)");
lines.push("  }");
lines.push("");
lines.push("  function getBookingsForDay(date: Date) {");
lines.push("    return bookings.filter(b => {");
lines.push("      if (!isSameDay(new Date(b.booking_date + 'T00:00:00'), date)) return false");
lines.push("      if (selectedPitch !== 'all' && b.pitch_id !== parseInt(selectedPitch)) return false");
lines.push("      if (selectedTeam !== 'all' && b.team_name !== selectedTeam) return false");
lines.push("      return true");
lines.push("    })");
lines.push("  }");
lines.push("");
lines.push("  function getCardStyle(booking: Booking): React.CSSProperties {");
lines.push("    if (booking.status === 'approved') {");
lines.push("      const colour = booking.pitch_colour || '#1a5c2e'");
lines.push("      return { backgroundColor: colour + '22', borderLeft: `4px solid ${colour}`, color: '#1a3a1a' }");
lines.push("    }");
lines.push("    if (booking.status === 'pending') {");
lines.push("      return { backgroundColor: '#fffbeb', borderLeft: '4px dashed #f59e0b', color: '#92400e' }");
lines.push("    }");
lines.push("    return { backgroundColor: '#f9fafb', borderLeft: '4px solid #d1d5db', color: '#6b7280' }");
lines.push("  }");
lines.push("");
lines.push("  function getMonthCardStyle(booking: Booking): React.CSSProperties {");
lines.push("    if (booking.status === 'approved') {");
lines.push("      const colour = booking.pitch_colour || '#1a5c2e'");
lines.push("      return { backgroundColor: colour, borderLeft: `3px solid ${colour}`, color: 'white' }");
lines.push("    }");
lines.push("    if (booking.status === 'pending') {");
lines.push("      return { backgroundColor: '#fffbeb', borderLeft: '3px dashed #f59e0b', color: '#92400e' }");
lines.push("    }");
lines.push("    return { backgroundColor: '#f3f4f6', borderLeft: '3px solid #9ca3af', color: '#6b7280' }");
lines.push("  }");
lines.push("");
lines.push("  const uniqueTeams = Array.from(new Set(bookings.map(b => b.team_name))).sort()");
lines.push("");
lines.push("  function renderMonthView() {");
lines.push("    const monthStart = startOfMonth(currentDate)");
lines.push("    const monthEnd = endOfMonth(currentDate)");
lines.push("    const startDate = startOfWeek(monthStart, { weekStartsOn: 1 })");
lines.push("    const endDate = endOfWeek(monthEnd, { weekStartsOn: 1 })");
lines.push("    const days: Date[] = []");
lines.push("    let day = startDate");
lines.push("    while (day <= endDate) { days.push(day); day = addDays(day, 1) }");
lines.push("    const weeks: Date[][] = []");
lines.push("    for (let i = 0; i < days.length; i += 7) weeks.push(days.slice(i, i + 7))");
lines.push("    return (");
lines.push("      <div className=\"month-grid-wrapper border border-gray-200 rounded-lg overflow-hidden\">");
lines.push("        <div className=\"grid grid-cols-7 bg-gray-900\">");
lines.push("          {['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d => (");
lines.push("            <div key={d} className=\"text-center text-xs font-semibold text-white py-3\">{d}</div>");
lines.push("          ))}");
lines.push("        </div>");
lines.push("        {weeks.map((week, wi) => (");
lines.push("          <div key={wi} className=\"grid grid-cols-7 border-t border-gray-200\">");
lines.push("            {week.map((day, di) => {");
lines.push("              const dayBookings = getBookingsForDay(day)");
lines.push("              const isCurrentMonth = isSameMonth(day, currentDate)");
lines.push("              const todayClass = isToday(day) ? 'bg-gray-900 text-white' : ''");
lines.push("              return (");
lines.push("                <div key={di} className={`min-h-24 p-1 border-l border-gray-200 ${!isCurrentMonth ? 'bg-gray-50' : 'bg-white'}`}>");
lines.push("                  <div className=\"flex justify-end\">");
lines.push("                    <span className={`text-xs font-medium w-6 h-6 flex items-center justify-center rounded-full ${todayClass} ${!isCurrentMonth ? 'text-gray-400' : 'text-gray-700'}`}>");
lines.push("                      {format(day, 'd')}");
lines.push("                    </span>");
lines.push("                  </div>");
lines.push("                  <div className=\"space-y-1 mt-1\">");
lines.push("                    {dayBookings.slice(0,3).map(booking => (");
lines.push("                      <div key={booking.id} onClick={() => setSelectedBooking(booking)} style={getMonthCardStyle(booking)} className=\"text-xs p-1 rounded cursor-pointer hover:opacity-80 transition-opacity\">");
lines.push("                        <div className=\"font-semibold truncate\">{booking.team_name}</div>");
lines.push("                        <div className=\"opacity-80\">{booking.start_time.slice(0,5)}</div>");
lines.push("                      </div>");
lines.push("                    ))}");
lines.push("                    {dayBookings.length > 3 && <div className=\"text-xs text-gray-500 pl-1\">+{dayBookings.length - 3} more</div>}");
lines.push("                  </div>");
lines.push("                </div>");
lines.push("              )");
lines.push("            })}");
lines.push("          </div>");
lines.push("        ))}");
lines.push("      </div>");
lines.push("    )");
lines.push("  }");
lines.push("");
lines.push("  function renderWeekView() {");
lines.push("    const weekStart = startOfWeek(currentDate, { weekStartsOn: 1 })");
lines.push("    const days = Array.from({ length: 7 }, (_, i) => addDays(weekStart, i))");
lines.push("    return (");
lines.push("      <div className=\"week-grid-wrapper border border-gray-200 rounded-lg overflow-hidden\">");
lines.push("        <div className=\"grid grid-cols-7 bg-gray-900\">");
lines.push("          {days.map((day, i) => (");
lines.push("            <div key={i} className=\"text-center py-3\">");
lines.push("              <div className=\"text-xs font-semibold text-gray-400\">{format(day, 'EEE').toUpperCase()}</div>");
lines.push("              <div className={`text-sm font-bold mt-1 w-8 h-8 flex items-center justify-center rounded-full mx-auto ${isToday(day) ? 'bg-white text-gray-900' : 'text-white'}`}>{format(day, 'd')}</div>");
lines.push("              <div className=\"text-xs text-gray-400\">{format(day, 'MMM')}</div>");
lines.push("            </div>");
lines.push("          ))}");
lines.push("        </div>");
lines.push("        <div className=\"grid grid-cols-7 divide-x divide-gray-200\">");
lines.push("          {days.map((day, di) => {");
lines.push("            const dayBookings = getBookingsForDay(day)");
lines.push("            return (");
lines.push("              <div key={di} className=\"min-h-48 p-2 space-y-2 bg-white\">");
lines.push("                {dayBookings.map(booking => (");
lines.push("                  <div key={booking.id} onClick={() => setSelectedBooking(booking)} style={getCardStyle(booking)} className=\"text-xs p-2 rounded cursor-pointer hover:opacity-80 transition-opacity\">");
lines.push("                    <div className=\"font-bold\" style={{color: booking.status === 'approved' ? booking.pitch_colour || '#1a5c2e' : 'inherit'}}>{booking.start_time.slice(0,5)}-{booking.end_time.slice(0,5)}</div>");
lines.push("                    <div className=\"font-semibold\">{booking.team_name}</div>");
lines.push("                    <div className=\"opacity-70\">{booking.booked_by} - {booking.pitch_name}</div>");
lines.push("                  </div>");
lines.push("                ))}");
lines.push("              </div>");
lines.push("            )");
lines.push("          })}");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    )");
lines.push("  }");
lines.push("");
lines.push("  return (");
lines.push("    <div>");
lines.push("      <div className=\"flex items-start justify-between mb-4\">");
lines.push("        <div>");
lines.push("          <h1 className=\"text-2xl font-bold text-gray-900\">Pitch Planner</h1>");
lines.push("          <p className=\"text-gray-500 text-sm\">St. Saviours GAA & LGFA</p>");
lines.push("        </div>");
lines.push("        <div className=\"flex gap-2\">");
lines.push("          <button className=\"border border-gray-300 px-4 py-2 rounded-lg text-sm hover:bg-gray-50\">Print / Save</button>");
lines.push("          <a href=\"/new-booking\" className=\"bg-gray-900 text-white px-4 py-2 rounded-lg text-sm font-semibold hover:bg-gray-700\">+ New Booking</a>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div className=\"flex items-center gap-4 mb-4 text-sm\">");
lines.push("        <span className=\"flex items-center gap-1\"><span className=\"w-3 h-3 rounded-full bg-green-700 inline-block\"></span> Booked</span>");
lines.push("        <span className=\"flex items-center gap-1\"><span className=\"w-3 h-3 rounded-full bg-amber-400 inline-block\"></span> Awaiting Approval</span>");
lines.push("        <span className=\"flex items-center gap-1\"><span className=\"w-3 h-3 rounded-full bg-gray-400 inline-block\"></span> Pitch Closed</span>");
lines.push("      </div>");
lines.push("      <div className=\"flex flex-wrap items-center gap-3 mb-4\">");
lines.push("        <select value={selectedPitch} onChange={e => setSelectedPitch(e.target.value)} className=\"border border-gray-300 rounded-lg px-3 py-2 text-sm\">");
lines.push("          <option value=\"all\">All Pitches</option>");
lines.push("          {pitches.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}");
lines.push("        </select>");
lines.push("        <select value={selectedTeam} onChange={e => setSelectedTeam(e.target.value)} className=\"border border-gray-300 rounded-lg px-3 py-2 text-sm\">");
lines.push("          <option value=\"all\">All Teams</option>");
lines.push("          {uniqueTeams.map(t => <option key={t} value={t}>{t}</option>)}");
lines.push("        </select>");
lines.push("      </div>");
lines.push("      <div className=\"flex items-center gap-3 mb-4\">");
lines.push("        <div className=\"flex border border-gray-300 rounded-lg overflow-hidden\">");
lines.push("          <button onClick={() => setView('week')} className={`px-4 py-2 text-sm font-medium ${view === 'week' ? 'bg-gray-900 text-white' : 'bg-white text-gray-700 hover:bg-gray-50'}`}>Week</button>");
lines.push("          <button onClick={() => setView('month')} className={`px-4 py-2 text-sm font-medium ${view === 'month' ? 'bg-gray-900 text-white' : 'bg-white text-gray-700 hover:bg-gray-50'}`}>Month</button>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div className=\"flex items-center justify-between mb-4\">");
lines.push("        <button onClick={() => setCurrentDate(view === 'month' ? subMonths(currentDate, 1) : subWeeks(currentDate, 1))} className=\"border border-gray-300 px-4 py-2 rounded-lg text-sm hover:bg-gray-50\">&larr; Prev</button>");
lines.push("        <h2 className=\"text-lg font-semibold text-gray-900\">{view === 'month' ? format(currentDate, 'MMMM yyyy') : 'This Week'}</h2>");
lines.push("        <button onClick={() => setCurrentDate(view === 'month' ? addMonths(currentDate, 1) : addWeeks(currentDate, 1))} className=\"border border-gray-300 px-4 py-2 rounded-lg text-sm hover:bg-gray-50\">Next &rarr;</button>");
lines.push("      </div>");
lines.push("      {loading ? <div className=\"text-center py-12 text-gray-500\">Loading bookings...</div> : view === 'month' ? renderMonthView() : renderWeekView()}");
lines.push("      {selectedBooking && (");
lines.push("        <BookingModal booking={selectedBooking} onClose={() => setSelectedBooking(null)} currentUserId={currentUserId} userRole={userRole} />");
lines.push("      )}");
lines.push("    </div>");
lines.push("  )");
lines.push("}");
fs.writeFileSync('components/PitchCalendar.tsx', lines.join('\n'), 'utf8');
console.log('Done - PitchCalendar rewritten');
